name: Build Corne Split Firmware

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ZEPHYR_SDK_VERSION: 0.17.4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            ninja-build gperf ccache dfu-util device-tree-compiler \
            python3-setuptools wget file unzip

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Install West
        run: |
          python3 -m pip install --upgrade pip
          pip install west
      - name: Install Zephyr Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install pyelftools


      - name: Cache Zephyr SDK
        id: cache-zephyr-sdk
        uses: actions/cache@v3
        with:
          path: /opt/zephyr-sdk
          key: ${{ runner.os }}-zephyr-sdk-v${{ env.ZEPHYR_SDK_VERSION }}
          restore-keys: ${{ runner.os }}-zephyr-sdk

      - name: Install Zephyr SDK
        if: steps.cache-zephyr-sdk.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZEPHYR_SDK_VERSION}/zephyr-sdk-${ZEPHYR_SDK_VERSION}_linux-x86_64.tar.xz
          tar xf zephyr-sdk-${ZEPHYR_SDK_VERSION}_linux-x86_64.tar.xz
          cd zephyr-sdk-${ZEPHYR_SDK_VERSION}
          ./setup.sh -h -c -t all
          echo "ZEPHYR_SDK_INSTALL_DIR=$(pwd)" >> $GITHUB_ENV
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('config/**') }}
          restore-keys: ${{ runner.os }}-ccache

      - name: Enable ccache
        run: |
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          echo "ZEPHYR_CCACHE=1" >> $GITHUB_ENV

      - name: Clone ZMK firmware
        run: |
          git clone --depth 1 --branch main https://github.com/zmkfirmware/zmk.git zmk

      - name: Initialize ZMK with West
        run: |
          cd zmk
          west init -l app
          west update

      - name: Build Left Half (Peripheral)
        run: |
          cd zmk/app
          west build -d ../../build-left -b nice_nano_v2 -- \
            -DZMK_CONFIG=../../config \
            -DSHIELD="corne_left nice_view_adapter nice_view" \
            -DCONFIG_ZMK_SPLIT=y

      - name: Build Right Half (Central + USB HID)
        run: |
          cd zmk/app
          west build -d ../../build-right -b nice_nano_v2 -- \
            -DZMK_CONFIG=../../config \
            -DSHIELD="corne_right nice_view_adapter nice_view" \
            -DCONFIG_ZMK_SPLIT=y \
            -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y \
            -DCONFIG_ZMK_USB=y

      - name: Upload corne_left.uf2
        uses: actions/upload-artifact@v4
        with:
          name: corne_left.uf2
          path: build-left/zephyr/zephyr.uf2

      - name: Upload corne_right.uf2
        uses: actions/upload-artifact@v4
        with:
          name: corne_right.uf2
          path: build-right/zephyr/zephyr.uf2
